baseURL = 'https://abxijth.github.io/'
languageCode = 'en-us'
title = 'Abhijith R Pillai'
theme = 'PaperMod'

[params]
  author = "Abhijith R Pillai"
  description = "Welcome to my portfolio!"
  defaultTheme = "auto"

[params.assets]
  favicon = "icon.ico"

  # Home Page Content
  [params.homeInfoParams]
    Title = "Myself, Abhijith R Pillai"
    Content = """Passionate about building, learning, and sharing."""

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Amfoss-Journey"
    url = "/amfoss-journey/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "Socials"
    url = "/socials/"
    weight = 5

